### ISSUE TITLE
SerialFLashStorage reliability for connection loss / power loss

### ISSUE THREAD

**Issue by DylanMeng** [arduino-libraries/WiFi101OTA#13]
Hi, I started using SerialFLashStorage for OTA update, the logic in SDU/SFU is great it will only remove the update file if the transfer is completed.

However, in Wifi101OTA with SerialFLashStorage I don’t see any logic to protect the quality of the update file. 
1.	The file name and the file size are generated at the start of the transfer.
2.	SDU/SFU will transfer any update.bin even if it is corrupted.

I encounter those problems during power/connection loss testing.

My initial idea was to compare the update.bin file size with the sent file size but the file size with SerialFlash look to be static.

The second idea was to rename the file when the transfer succeeds but I don’t think it’s possible with SerialFLash...

Well, what would be the best method to make SerialFLashStorage more reliable?

Thanks!

**Comment by facchinm** [comment]
The only "hard" limitation we have is on Second stage bootloader (SDU/SFU) size (which is capped at 16KB). If you fit any security check (like requiring a checksum on the file and calculating before applying) inside this limitation the issue can be solved quite easily. 

In fact, the validity of update can also be checked inside the sketch but it's a bit less robust.

Adding such a check is out of the scope of this library, since different production-like scenarios are likely to have different requirements (checksum algorithm and so on) so we didn't add one to keep things simple :slightly_smiling_face:

**Comment by DylanMeng** [comment]
Great idea, I will try to find an optimal store place for the know checksum variable and add a checksum security check in the SDU/SFU to fix my problem. I should be able to do it under 16Kb.

Thanks again!
